In [1]:
import ai_matrix_ops as ops
import numpy as np
from PIL import Image


image_matrix = np.array([[10, 20, 30],
                         [40, 50, 60],
                         [70, 80, 90]])

compressed_image = ops.matrix_multiply(ops.matrix_multiply(ops.matrix_decomposition(image_matrix)[0][:, :1], np.diag(ops.matrix_decomposition(image_matrix)[1][:1])), ops.matrix_decomposition(image_matrix)[2][:1, :])
print("Compressed image:")
print(compressed_image)
print()
pseudo_inverse_matrix = ops.matrix_multiply(ops.matrix_multiply(ops.matrix_decomposition(image_matrix)[2].T, np.diag(1 /ops.matrix_decomposition(image_matrix)[1])), ops.matrix_decomposition(image_matrix)[0].T)
print("Pseudo-inverse matrix:")
print(pseudo_inverse_matrix)

print()
determinant = ops.matrix_determinant(image_matrix)
print("Image determinant:", determinant)


print()
optimal_threshold = ops.matrix_rank(image_matrix) // 2
print("Optimal threshold for compression:", optimal_threshold)


print()
U, S, V = ops.matrix_decomposition(image_matrix)
print("Singular values:", S)
print()

rank = ops.matrix_rank(image_matrix)
print("Image rank:", rank)
print()

norm = ops.matrix_norm_calculation_2_norm(image_matrix)
print("Image norm:", norm)

Compressed image:
[[17.36217794 20.71742465 24.07267136]
 [42.07152799 50.20186489 58.33220179]
 [66.78087804 79.68630513 92.59173222]]

Pseudo-inverse matrix:
[[-4.24359383e+13  8.48718765e+13 -4.24359383e+13]
 [ 8.48718765e+13 -1.69743753e+14  8.48718765e+13]
 [-4.24359383e+13  8.48718765e+13 -4.24359383e+13]]

Image determinant: -4.263256414560599e-12

Optimal threshold for compression: 1

Singular values: [1.68481034e+02 1.06836951e+01 3.92748867e-15]

Image rank: 2

Image norm: 168.48103352614208


Below is the analysis of the use case presented in the code:

---

## Use Case Analysis: Image Compression and Analysis

The provided code demonstrates the use of a custom library `ai_matrix_ops` for performing various linear algebra operations on an example grayscale image represented as a matrix. The primary objectives of this use case are image compression and analysis using Singular Value Decomposition (SVD) and other linear algebra operations.

### 1. Compressed Image
- **Purpose**: The purpose of this operation is to compress the image matrix by reducing its dimensions while preserving important information.
- **Approach**: SVD is performed on the image matrix, and the singular value matrix and left and right singular vectors are truncated to retain only a subset of singular values and vectors. The compressed image is reconstructed using the truncated matrices.
- **Implementation**: This is achieved by using the `matrix_decomposition` function to obtain the singular value decomposition of the image matrix, and then performing matrix multiplication operations to reconstruct the compressed image.

### 2. Pseudo-Inverse Matrix
- **Purpose**: Calculating the pseudo-inverse of the image matrix is useful for various image processing tasks, such as image restoration and solving linear least squares problems.
- **Approach**: The pseudo-inverse is obtained by taking the reciprocal of non-zero singular values and performing matrix multiplication operations on the truncated singular vectors and singular value matrix.
- **Implementation**: This operation involves using the `matrix_decomposition` function to obtain the SVD of the image matrix and then performing matrix multiplication operations to compute the pseudo-inverse.

### 3. Image Determinant
- **Purpose**: Calculating the determinant of the image matrix provides information about the volume scaling factor of the linear transformation represented by the matrix.
- **Approach**: The determinant of the image matrix is directly computed using the `matrix_determinant` function.
- **Implementation**: This operation involves calling the `matrix_determinant` function with the image matrix as input.

### 4. Optimal Threshold for Compression
- **Purpose**: Determining the optimal threshold for compression is crucial for balancing between image quality and compression ratio.
- **Approach**: The optimal threshold is set as half of the rank of the image matrix.
- **Implementation**: This operation involves calling the `matrix_rank` function to determine the rank of the image matrix and then computing the optimal threshold.

### 5. Singular Values and Image Rank
- **Purpose**: Obtaining the singular values and rank of the image matrix provides insights into its structure and properties.
- **Approach**: The singular values are obtained using the `matrix_decomposition` function, and the rank is determined using the `matrix_rank` function.
- **Implementation**: These operations involve calling the `matrix_decomposition` and `matrix_rank` functions with the image matrix as input.

### 6. Image Norm
- **Purpose**: Calculating the norm of the image matrix helps in quantifying its magnitude and behavior under compression.
- **Approach**: The 2-norm (largest singular value) of the image matrix is computed.
- **Implementation**: This operation involves calling the `matrix_norm_calculation_2_norm` function with the image matrix as input.

### Conclusion
The provided code demonstrates the usage of linear algebra operations for image compression and analysis. By leveraging SVD and other matrix operations, it achieves tasks such as compression, pseudo-inverse calculation, determinant computation, rank determination, and norm calculation. These operations provide valuable insights into the image structure and enable effective image processing and analysis.

--- 

This analysis provides a detailed understanding of the purpose, approach, and implementation of each operation in the given use case. It highlights the significance of linear algebra in image processing and analysis tasks.